export const BOM = [
  {
    name: 'Stół',
    level: 0,
    required: 1,
    parent: null,
    realization_time: 1,
    stock: 2,
  },
  {
    name: 'Noga',
    level: 1,
    required: 4,
    parent: 'Stół',
    realization_time: 2,
    stock: 40,
    partSize: 120,
  },
  {
    name: 'Blat',
    level: 1,
    required: 1,
    parent: 'Stół',
    realization_time: 3,
    stock: 22,
    partSize: 40,
  },
  {
    name: 'Płyta',
    level: 2,
    required: 1,
    parent: 'Blat',
    realization_time: 1,
    stock: 10,
    partSize: 50,
  },
];

// export const BOM = [
//   {
//     name: 'Rower',
//     level: 0,
//     required: 1,
//     parent: null,
//     realization_time: 1,
//     stock: 2,
//   },
//   {
//     name: 'Koło',
//     level: 1,
//     required: 2,
//     parent: 'Rower',
//     realization_time: 2,
//     stock: 40,
//     partSize: 120,
//   },
//   {
//     name: 'Szprycha',
//     level: 2,
//     required: 32,
//     parent: 'Koło',
//     realization_time: 2,
//     stock: 22,
//     partSize: 40,
//   },
//   {
//     name: 'Opona',
//     level: 2,
//     required: 1,
//     parent: 'Koło',
//     realization_time: 1,
//     stock: 22,
//     partSize: 40,
//   },
//   {
//     name: 'Rama',
//     level: 1,
//     required: 1,
//     parent: 'Rower',
//     realization_time: 2,
//     stock: 22,
//     partSize: 40,
//   },
//   {
//     name: 'Kierownica',
//     level: 2,
//     required: 1,
//     parent: 'Rama',
//     realization_time: 1,
//     stock: 10,
//     partSize: 50,
//   },
//   {
//     name: 'Siodło',
//     level: 2,
//     required: 1,
//     parent: 'Rama',
//     realization_time: 1,
//     stock: 10,
//     partSize: 50,
//   },
//   {
//     name: 'Hamulec',
//     level: 2,
//     required: 2,
//     parent: 'Rama',
//     realization_time: 2,
//     stock: 40,
//     partSize: 120,
//   },
//   {
//     name: 'Pedał',
//     level: 2,
//     required: 2,
//     parent: 'Rama',
//     realization_time: 1,
//     stock: 10,
//     partSize: 50,
//   },
//   {
//     name: 'Łańcuch',
//     level: 1,
//     required: 1,
//     parent: 'Rower',
//     realization_time: 1,
//     stock: 10,
//     partSize: 50,
//   },
// ];

export let GHP = {
  schedule: [
    { week: 1, demand: 0, production: 0, stock: 0 },
    { week: 2, demand: 0, production: 0, stock: 0 },
    { week: 3, demand: 0, production: 0, stock: 0 },
    { week: 4, demand: 0, production: 0, stock: 0 },
    { week: 5, demand: 20, production: 28, stock: 0 },
    { week: 6, demand: 0, production: 0, stock: 0 },
    { week: 7, demand: 40, production: 30, stock: 0 },
    { week: 8, demand: 0, production: 0, stock: 0 },
    { week: 9, demand: 0, production: 0, stock: 0 },
    { week: 10, demand: 0, production: 0, stock: 0 },
  ],
};

// export let GHP = {
//   schedule: [
//     { week: 1, demand: 0, production: 0, stock: 0 },
//     { week: 2, demand: 0, production: 0, stock: 0 },
//     { week: 3, demand: 0, production: 0, stock: 0 },
//     { week: 4, demand: 0, production: 0, stock: 0 },
//     { week: 5, demand: 0, production: 0, stock: 0 },
//     { week: 6, demand: 0, production: 0, stock: 0 },
//     { week: 7, demand: 0, production: 0, stock: 0 },
//     { week: 8, demand: 0, production: 0, stock: 0 },
//     { week: 9, demand: 10, production: 20, stock: 0 },
//     { week: 10, demand: 0, production: 0, stock: 0 },
//   ],
// };
